---
title: "scrapping_data"
author: "Yucong Gao"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
library(jsonlite)
library(httr)
library(tidyverse)
```

## Function for Data Scrapping


```{r}
scrapping_data = function(url) {
  headers = headers = c(
  `Connection` = 'keep-alive',
  `Accept` = 'application/json, text/plain, */*',
  `x-nba-stats-token` = 'true',
  `X-NewRelic-ID` = 'VQECWF5UChAHUlNTBwgBVw==',
  `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 
  `x-nba-stats-origin` = 'stats',
  `Sec-Fetch-Site` = 'same-origin',
  `Sec-Fetch-Mode` = 'cors',
  `Referer` = 'https://stats.nba.com/players/leaguedashplayerbiostats/',
  `Accept-Encoding` = 'gzip, deflate, br',
  `Accept-Language` = 'en-US,en;q=0.9')
  response = GET(url, add_headers(headers))
  data = fromJSON(content(response, as = "text"))
  df = data.frame(data$resultSets$rowSet[[1]], stringAsFactors = FALSE)
  names(df) = tolower(data$resultSets$headers[[1]])
  return(df)
}

drop_last_column = function(df) {
  df = df %>% select(- names(df)[[length(names(df))]])
  return(df)
}



url_new = "https://stats.nba.com/stats/teamgamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlusMinus=N&Rank=N&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&VsConference=&VsDivision="

box_score_21_22 = 
  scrapping_data(url_new) %>% 
  drop_last_column()

write_csv(box_score_21_22, "./data2/box_score_21_22.csv")
```

```{r}

transition_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=Transition&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")

write_csv(transition_21_22, "./data2/transition_21_22.csv")

iso_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=Isolation&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

write_csv(iso_21_22, "./data2/iso_21_22.csv")

prbh_21_22 = scrapping_data(("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=PRBallHandler&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive")) %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

write_csv(prbh_21_22, "./data2/prbh_21_22.csv")

prrm_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=PRRollman&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

write_csv(prrm_21_22, "./data2/prrm_21_22.csv")

defend_21_22 = scrapping_data("https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Defense&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")

write_csv(defend_21_22, "./data2/defend_21_22.csv")

pass_21_22 = scrapping_data("https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Passing&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")

write_csv(pass_21_22, "./data2/pass_21_22.csv")



```

