---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(jsonlite)
library(httr)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(shiny)
```

```{r, include=FALSE}
box_score_all = read_csv("./data2/box_score_all.csv")

box_score_all = 
  box_score_all %>% 
  janitor::clean_names() %>% 
  select(-contains("rank")) %>% 
  select(
    season_year, 
    team_abbreviation, 
    wl, 
    pts, 
    ast, 
    tov, 
    fgm, 
    fga, 
    fg3m, 
    fg3a
    ) %>%
  mutate(
    win = case_when(wl == "W" ~ 1, TRUE~0),
    game_num = 1,
    fg3a_p = round(fg3a/fga, digits = 3),
    conference = case_when(
      team_abbreviation %in% c("UTA","PHX","LAC","DEN","DAL","LAL","POR","GSW","SAS","MEM","NOP","SAC","MIN","OKC","HOU","NOH","SEA","NOK","CHH")~"west",
      team_abbreviation %in% c("PHI","BKN","MIL","ATL","NYK","MIA","BOS","IND","WAS","CHI","TOR","CLE","ORL","DET","NJN","CHA")~"east") # divide into east and west conference
    ) %>% 
  group_by(season_year, team_abbreviation, conference) %>% 
  summarise(
    wins = sum(win), 
    games = sum(game_num), 
    games_should = 82, 
    pts_avg = round(mean(pts), digits = 1), 
    ast_avg = round(mean(ast), digits = 1),
    tov_avg = round(mean(tov), digits = 1),
    fgm_total = sum(fgm), 
    fga_total = sum(fga), 
    fg3m_total = sum(fg3m), 
    fg3a_total = sum(fg3a)
    ) %>% 
  mutate(wins_revised = round(wins/games*games_should,0)) %>% # due to labor negotiation in 2011-12, COVID-19.
  relocate(season_year, team_abbreviation, conference, wins, wins_revised, everything()) %>% 
  arrange(desc(season_year),desc(wins)) %>% 
  mutate(team_abbreviation = str_replace(team_abbreviation, "NOH", "NOP"), 
         team_abbreviation = str_replace(team_abbreviation, "NJN", "BKN"), 
         fg3_p = fg3a_total/fga_total, 
         fg3_r = fg3m_total/fg3a_total) %>% 
  select(season_year, team_abbreviation, 
         conference, wins_revised, pts_avg, 
         ast_avg, tov_avg,fg3_p, fg3_r, 
         fg3a_total, fg3m_total) %>% 
  ungroup()

```


```{r, include=FALSE}
defensive_impact_df = read_csv("./data2/defensive_impact_df.csv")
passing_df = read_csv("./data2/pass_df.csv") 
isolation_df = read_csv("./data2/isol_df.csv")
pick_roll_baller_df = read_csv("./data2/prbh_df.csv")
pick_roll_roller_df = read_csv("./data2/prrm_df.csv")
transition_df = read_csv("./data2/transition_df.csv")

trans_df = 
  transition_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_trans = poss)

pass_df = 
  passing_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, passes_made)

isol_df = 
  isolation_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_iso = poss)

prbh_df = 
  pick_roll_baller_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_prb = poss)

prrm_df = 
  pick_roll_roller_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_prr = poss)

defend_df = 
  defensive_impact_df %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, stl, blk, dreb)
```


```{r, include=FALSE}
avg_df = 
  box_score_all %>%
  left_join(defend_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(prrm_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(prbh_df, by = c("season_year","team_abbreviation")) %>%
  left_join(isol_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(pass_df, by = c("season_year","team_abbreviation")) %>%
  left_join(trans_df, by = c("season_year","team_abbreviation")) %>% 
  drop_na(poss_trans, passes_made, poss_iso, poss_prb, poss_prr, stl, blk, dreb) %>% 
  mutate(
    poss_pr = poss_prr + poss_prb
  ) %>% 
  select(-poss_prr, -poss_prb) %>% 
  rename(team = team_abbreviation, 
         wins = wins_revised, 
         average_score = pts_avg, 
         assistance = ast_avg, 
         turnover = tov_avg, 
         three_field_goal_attempt = fg3_p)

conf_rank = 
  avg_df %>% 
  group_by(season_year, conference) %>% 
  mutate(conf_rank = row_number()) %>% 
  ungroup() %>% 
  select(season_year, team, conference, conf_rank) %>% 
  mutate(play_off_team = case_when(
           conf_rank <= 8 ~ "playoff", 
           conf_rank > 8 ~ "non-playoff"
         ), 
         play_off_team = fct_relevel(play_off_team, c("playoff", "non-playoff"))) 

regular_season_viz = 
  avg_df %>% 
  pivot_longer(wins:poss_pr, 
               names_to = "parameters", 
               values_to = "team_value") %>% 
  left_join(conf_rank, by = c("season_year", "team", "conference"))



```

```{r regression model, include=FALSE}
predict_df = avg_df 

model = lm(data = predict_df, wins ~ average_score + turnover + three_field_goal_attempt + fg3_r + stl + blk + dreb + poss_trans + poss_iso + poss_pr + assistance)

```

```{r new data, include=FALSE}
scrapping_data = function(url) {
  headers = headers = c(
  `Connection` = 'keep-alive',
  `Accept` = 'application/json, text/plain, */*',
  `x-nba-stats-token` = 'true',
  `X-NewRelic-ID` = 'VQECWF5UChAHUlNTBwgBVw==',
  `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 
  `x-nba-stats-origin` = 'stats',
  `Sec-Fetch-Site` = 'same-origin',
  `Sec-Fetch-Mode` = 'cors',
  `Referer` = 'https://stats.nba.com/players/leaguedashplayerbiostats/',
  `Accept-Encoding` = 'gzip, deflate, br',
  `Accept-Language` = 'en-US,en;q=0.9')
  response = GET(url, add_headers(headers))
  data = fromJSON(content(response, as = "text"))
  df = data.frame(data$resultSets$rowSet[[1]], stringAsFactors = FALSE)
  names(df) = tolower(data$resultSets$headers[[1]])
  return(df)
}

drop_last_column = function(df) {
  df = df %>% select(- names(df)[[length(names(df))]])
  return(df)
}



url_new = "https://stats.nba.com/stats/teamgamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlusMinus=N&Rank=N&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&VsConference=&VsDivision="

box_score_21_22 = 
  scrapping_data(url_new) %>% 
  drop_last_column()

transition_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=Transition&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")

iso_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=Isolation&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

prbh_21_22 = scrapping_data(("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=PRBallHandler&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive")) %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

prrm_21_22 = scrapping_data("https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=PerGame&PlayType=PRRollman&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2021-22&TypeGrouping=offensive") %>% drop_last_column()%>% 
  mutate(season_year = "2021-22")

defend_21_22 = scrapping_data("https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Defense&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")

pass_21_22 = scrapping_data("https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Passing&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=") %>% 
  drop_last_column() %>% 
  mutate(season_year = "2021-22")


# data wrangling for new season data
box_score_21_22 = 
  box_score_21_22 %>% 
  select(
    season_year, 
    team_abbreviation, 
    wl, 
    pts, 
    ast, 
    tov, 
    fgm, 
    fga, 
    fg3m, 
    fg3a
    ) %>%
  mutate(
    win = case_when(wl == "W" ~ 1, TRUE~0),
    game_num = 1,
    fg3a_p = round(as.numeric(fg3a)/as.numeric(fga), digits = 3),
    conference = case_when(
      team_abbreviation %in% c("UTA","PHX","LAC","DEN","DAL","LAL","POR","GSW","SAS","MEM","NOP","SAC","MIN","OKC","HOU","NOH","SEA","NOK","CHH")~"west",
      team_abbreviation %in% c("PHI","BKN","MIL","ATL","NYK","MIA","BOS","IND","WAS","CHI","TOR","CLE","ORL","DET","NJN","CHA")~"east") # divide into east and west conference
    ) %>% 
  group_by(season_year, team_abbreviation, conference) %>% 
  summarise(
    wins = sum(win), 
    games = sum(game_num), 
    average_score = round(mean(as.numeric(pts)), digits = 1), 
    assistance = round(mean(as.numeric(ast)), digits = 1),
    turnover = round(mean(as.numeric(tov)), digits = 1),
    fgm_total = sum(as.numeric(fgm)), 
    fga_total = sum(as.numeric(fga)), 
    fg3m_total = sum(as.numeric(fg3m)), 
    fg3a_total = sum(as.numeric(fg3a))
    ) %>% 
  relocate(season_year, team_abbreviation, conference, wins, everything()) %>% 
  arrange(desc(season_year),desc(wins))

box_score_21_22 = 
  box_score_21_22  %>% 
  mutate(three_field_goal_attempt = fg3a_total/fga_total, fg3_r = fg3m_total/fg3a_total) %>%
  select(season_year, team_abbreviation, conference, average_score, assistance, turnover,three_field_goal_attempt, fg3_r, fg3a_total, fg3m_total)


trans_df = 
  transition_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_trans = poss)

pass_df = 
  pass_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, passes_made)

isol_df = iso_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>%
  rename(poss_iso = poss)

prbh_df = 
  prbh_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_prb = poss)

prrm_df = 
  prrm_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, poss) %>% 
  rename(poss_prr = poss)

defend_df = 
  defend_21_22 %>% 
  janitor::clean_names() %>% 
  select(season_year, team_abbreviation, stl, blk, dreb)

new_season_df = 
  box_score_21_22 %>%
  left_join(defend_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(prrm_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(prbh_df, by = c("season_year","team_abbreviation")) %>%
  left_join(isol_df, by = c("season_year","team_abbreviation")) %>% 
  left_join(pass_df, by = c("season_year","team_abbreviation")) %>%
  left_join(trans_df, by = c("season_year","team_abbreviation")) %>% 
  drop_na(poss_trans, passes_made, poss_iso, poss_prb, poss_prr, stl, blk, dreb) %>% 
  mutate(
    poss_pr = as.numeric(poss_prr) + as.numeric(poss_prb)
  ) %>% 
  select(-poss_prr, -poss_prb) %>% 
  mutate(stl = as.numeric(stl), 
         blk = as.numeric(blk), 
         dreb = as.numeric(dreb), 
         poss_iso = as.numeric(poss_iso), 
         passes_made = as.numeric(passes_made), 
         poss_trans = as.numeric(poss_trans))

rank = c(1:15)
prediction_21_22 = 
  modelr::add_predictions(new_season_df, model) %>% select(conference, pred) %>% 
  arrange(desc(pred)) 

```

```{r, include=FALSE}
prediction_21_22 = 
  prediction_21_22 %>% 
  group_by(season_year, conference) %>% 
  mutate(rank = row_number())
```

```{r, include=FALSE}
prediction_21_22 %>% 
  ungroup() %>% 
  filter(team_abbreviation %in% "BOS") %>% 
  pull(rank)

```


Column {.sidebar} 
-----------------------------------------------------------------------

```{r}
parameter_choices = 
  regular_season_viz %>% 
  distinct(parameters) %>% 
  pull()

selectInput(
  "parameter_choices", 
  label = h3("Select Parameter(s)"), 
  choices = parameter_choices, 
  selected = "wins") #default value

team_choices = 
  regular_season_viz %>%
  distinct(team) %>% 
  pull()

selectInput(
  "team_choices", 
  label = h3("Select Team(s)"), 
  choices = team_choices, 
  selected = "NYK", 
  multiple = TRUE)


```



Column {data-width=1000}
-----------------------------------------------------------------------

### Average Play Data by Teams in the Last 8 Seasons

```{r}
renderPlotly({
  
  regular_season_viz %>% 
    filter(
      parameters == input[["parameter_choices"]], 
      team %in% input[["team_choices"]]
    ) %>% 
    pivot_wider(
    names_from = parameters, 
    values_from = team_value
  ) %>% 
    rename(selected_parameter = input[["parameter_choices"]]) %>% 
    plot_ly(x = ~ season_year, y = ~ selected_parameter, type = "scatter", mode = "line", 
            color = ~ team, alpha = .5)
})

```

### 2021-22 Regular Season Ranking Prediction
```{r}
renderTable({
  prediction_21_22 %>% 
    ungroup() %>% 
    filter(team_abbreviation %in% input[["team_choices"]]) %>% 
    select(team_abbreviation, conference, rank)
})



```

